### ISSUE TITLE
Panics with X.org

### ISSUE THREAD

**Issue by arrowd** [amshafer/nvidia-driver#2]
When trying out `nvidia-drm` with X server I got following panics.

The first one is when I did not load `i915kms` at all:

![20221125_083826](https://user-images.githubusercontent.com/1528094/203911663-a0580d9f-5904-4ea2-8ee0-c1ff0de30c39.jpg)

Then I first loaded `nvidia-drm` and then `i915kms` and got this:

![20221125_084234](https://user-images.githubusercontent.com/1528094/203912719-0ae7ced7-4d91-441b-afb4-9637f943ed39.jpg)

Finally, I first loaded `i915kms` and then `nvidia-drm` and it worked.

**Comment by amshafer** [comment]
Thanks, yes this reminds me of an issue with module load order that I thought I had solved. I'll take a look. Could you please include more info on the system? Most importantly ~~FreeBSD and~~ drm-kmod versions.

There's a `nvidia-bug-report.sh` tool that comes with the NVIDIA driver that will grab dmesg and other logs and bundle it up into a tarball, so if you feel comfortable sharing that it's an easy way to grab everything.

**Comment by amshafer** [comment]
Should be resolved as of the latest commit, could you please give that a try and reopen if you encounter more issues?

**Comment by arrowd** [comment]
Crashes are gone in both cases, however X also doesn't start in both cases. It now is unable to find appropriate video driver and bails out. `sysctl hw.dri` show that there is only `hw.dri.0.nvidia-drm` and no i915kms. `kldunload nvidia-drm` resulted in another panic.

Only when I loaded `i915kms` first and `nvidia-drm` second, I get both items in `sysctl hw.dri`. Not sure if this is worth reopening.

**Comment by amshafer** [comment]
X won't work without i915 loaded for sure. The intel GPU drives the internal display (eDP-1) and without it there's no way to present anything there. The order dependency you mention is odd, I didn't notice that even though I tried loading both ways, but I'll see if I can reproduce it.
